<a href="https://colab.research.google.com/github/gautamstrike789/MachineLearningPractice/blob/main/exercises/machine-learning/unsupervised-learning/KMeansclustering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clustering
You should build an end-to-end machine learning pipeline using a clustering model. In particular, you should do the following:
- Load the `customers` dataset using [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html). You can find this dataset in the datasets folder.
- Conduct data exploration, data preprocessing, and feature engineering if necessary.
- Choose a few clustering algorithms, such as [k-means](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html), [hdbscan](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.HDBSCAN.html), and [agglomerative clustering](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.AgglomerativeClustering.html).
- Train and evaluate clustering models (i.e., the clustering algorithm and its hyperparameters) to find out the best-performing model using clustering evaluation metrics, such as [elbow method](https://www.scikit-yb.org/en/latest/api/cluster/elbow.html) and the [silhouette score](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.silhouette_score.html).
- Check the documentation to identify the most important hyperparameters, attributes, and methods of the model. Use them in practice.

# Importing Libraries

In [10]:
import pandas as pd
import sklearn.metrics
import sklearn.cluster
import sklearn.preprocessing
import sklearn.model_selection
import plotly.graph_objects as go

# Loading Dataset

In [8]:
df = pd.read_csv("/content/customers.csv")
df = df.set_index("ID")
df.head(5)

,Sex,Marital status,Age,Education,Income,Occupation,Settlement size
ID,,,,,,,
100000001,0,0,67,2,124670,1,2
100000002,1,1,22,1,150773,1,2
100000003,0,0,49,1,89210,0,0
100000004,0,0,45,1,171565,1,1
100000005,0,0,53,1,149031,1,1

# Feature Scaling

In [11]:
scaler = sklearn.preprocessing.StandardScaler()
scaler.fit(df)
x = scaler.transform(df)

# Training Model

In [12]:
model = sklearn.cluster.KMeans(n_clusters=2)
model.fit(x)
print(model.inertia_)
print(model.labels_)
print(model.cluster_centers_)

10515.072861900107
[1 0 0 ... 0 0 0]
[[ 0.54628323  0.35691993 -0.27276608  0.01956802 -0.50387214 -0.5322566
  -0.56097476]
 [-0.70379281 -0.45983049  0.35141259 -0.02521006  0.64915335  0.68572189
   0.72272034]]

In [13]:
df["cluster id"] = model.labels_
df.head()

,Sex,Marital status,Age,Education,Income,Occupation,Settlement size,cluster id
ID,,,,,,,,
100000001,0,0,67,2,124670,1,2,1
100000002,1,1,22,1,150773,1,2,0
100000003,0,0,49,1,89210,0,0,0
100000004,0,0,45,1,171565,1,1,1
100000005,0,0,53,1,149031,1,1,1

# Identifying the Number of Clusters

## Elbow Method

In [15]:
K_list = []
elbow_scores = []
for k in range(2,51): #[2, 3, 4,..... 50]
    K_list.append(k)
    model = sklearn.cluster.KMeans(n_clusters=k)
    model.fit(x)
    es = model.inertia_
    elbow_scores.append(es)
fig = go.Figure(data=go.Scatter(x=K_list, y=elbow_scores))
fig.show()

## Silhouette Score

In [16]:
K_list = []
sil_scores = []
for k in range(2,51): #[2, 3, 4,..... 50]
    K_list.append(k)
    model = sklearn.cluster.KMeans(n_clusters=k)
    model.fit(x)
    y_predicted = model.predict(x)
    ss = sklearn.metrics.silhouette_score(x, y_predicted)
    sil_scores.append(ss)
fig = go.Figure(data=go.Scatter(x=K_list, y=sil_scores))
fig.show()